opt_in_rules:
  - local_doc_comment
  - missing_docs

missing_docs:
  warning:
    - open
    - public
    - internal
    - fileprivate
    - private
  excludes_extensions: false
  excludes_inherited_types: false
