name: Swift

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.8'
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: SwiftLint
      uses: raphaelbussa/swiftlint-action@main
      with:
        subcommand: lint --strict # Pass any subcommand needed
